# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CI - Build on changes in Docker container

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: 
      image: shilga/raspberry-pi-pico-gbdk-docker:v0.3

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo 'github.workspace = ${{ github.workspace }}'
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo 'runner.workspace = ${{ runner.workspace }}'
        echo "RUNNER_WORKSPACE = $RUNNER_WORKSPACE"
        cmake -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
        echo 'github.workspace = ${{ github.workspace }}'
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo 'runner.workspace = ${{ runner.workspace }}'
        echo "RUNNER_WORKSPACE = $RUNNER_WORKSPACE"
        cmake --build $GITHUB_WORKSPACE/build --config ${{env.BUILD_TYPE}}

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rp2040-gameboy-cartridge-binaries-${{env.GITHUB_SHA}}
        path: |
          ${{env.GITHUB_WORKSPACE}}/build/*.bin
          ${{env.GITHUB_WORKSPACE}}/build/*.elf
          ${{env.GITHUB_WORKSPACE}}/build/*.elf.map
          ${{env.GITHUB_WORKSPACE}}/build/*.hex
          ${{env.GITHUB_WORKSPACE}}/build/*.uf2
